CREATE DATABASE `grafana` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE `envreport` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `environment` varchar(45) NOT NULL,
  `packages` text,
  `author` text,
  `publish` text,
  `publish00` text,
  `publish01` text,
  `publish02` text,
  `publish03` text,
  `publish04` text,
  `hybris` text,
  `hybrishmc` varchar(45) DEFAULT NULL,
  `hybrisapi01` varchar(45) DEFAULT NULL,
  `hybrisapi02` varchar(45) DEFAULT NULL,
  `hybrisapi03` varchar(45) DEFAULT NULL,
  `hybrisapi04` varchar(45) DEFAULT NULL,
  `cookbook` text,
  `cookbook_version` text,
  `cookbook_status` text,
  `author0` text,
  `publishjobrunner0` text,
  `publish0` text,
  `publish1` text,
  `publish2` text,
  `publish3` text,
  `hybrisbackoffice0` text,
  `hybris0` text,
  `hybris1` text,
  `hybris2` text,
  `hybris3` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `idx_new_table_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=latin1

CREATE TABLE `envreportblue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `environment` varchar(45) NOT NULL,
  `cookbook` text,
  `cookbook_version` text,
  `cookbook_status` text,
  `packages` text,
  `author0` text,
  `publishjobrunner0` text,
  `publish0` text,
  `publish1` text,
  `publish2` text,
  `publish3` text,
  `hybrisbackoffice0` text,
  `hybris0` text,
  `hybris1` text,
  `hybris2` text,
  `hybris3` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `idx_new_table_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=latin1

